Rails Form Project
FelipeEnne/Re-former pull request #1
Opened 2019-12-12 17:39 UTC by adaorachi

In this project, we created the following Rails Forms:

- Using HTML form tags

- Using rails helper method:  form_tag

- Using rails helper method: form_for

This is the first draft of this project. kindly review it as we wait for your response.

2019-12-13 03:58 UTC, efrapp requested changes
## Hi @adaorachi and @FelipeEnne 👋

Guys fabulous job on this project. You just have one small thing to do, please check my comments below.

As you finished this project fast I want to challenge you to do something: as you can see the `new` and the `edit` views have the same code so can you unify them in one partial to reuse it for both actions? This is optional but as you have one pending task to do it is a good opportunity to try this.

Please, send a new code review when you are done.

Have a great day!

**Status:** `Changes required`

2019-12-13 03:58 UTC, efrapp commented on app/controllers/users_controller.rb
> +      redirect_to users_path
This should redirect to: `edit_user_path`.

2019-12-13 03:58 UTC, efrapp commented on app/views/users/new.html.erb
> +  <p>
[`Optional`] It would be nice if you put this at the beginning of the file, thus, you can take advantage of it for all the forms.

2019-12-13 03:58 UTC, efrapp commented on app/views/users/new.html.erb
> +<%= form_tag("/users", method: "POST") do %>
`[Optional]` as you are using the helper methods here, you can use the helper path too instead fo `/users`.

2019-12-14 05:50 UTC, bolah2009 approved these changes
Good job implementing the suggested changes, It's a 👍🏾 from me team!

### :heavy_check_mark: Approved!

Good luck with your next projects. :star2: 

Cheers
[Bola](https://bolabuari.com/)

2019-12-16 12:44 UTC, merged